- name: Autenticação no Docker Hub
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
  uses: docker/login-action@v3.0.0
  with:
    username: ${{secrets.DOCKERHUB_USERNAME}}
    password: ${{secrets.DOCKERHUB_PASSWORD}}
